---
title: "time_visualizations"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r, fig.height=10, fig.width=10}
JOB_CODES <- c('11'='Management', '13'='Financial Operations', '23'='Legal',
               '15'='Computer and Maths', '16'='Architecture and Engineering',
               '17'='Life', '18'='Physical', '19'='Life, Physical, and Social Science',
               '21'='Community and Social Service', '25'='Educational Instruction and Library', 
               '27'='Arts, Design, Entertainment, Sports, and Media', '29'='Healthcare',
               '31'='Healthcare Support', '33'='Protective Service', '35'='Food Preparation and Serving',
               '37'='Building, Cleaning and Maintenance', '39'='Personal Care', '41'='Sales', 
               '43'='Office and Administrative Support', '45'='Farming, Fishing and Forestry',
               '47'='Construction and Extraction Occupations', '49'='Installation, Maintenance and Repair',
               '51'='Production Occupations', '53'='Transportation and Material Moving', '55'='Military'
              )

library(dplyr)
x <- list()
START_YEAR <- 2009
END_YEAR <- 2020
count_applications <- list()
library(ggplot2)
library(ggalluvial)
df <- data.frame()
for(year in START_YEAR:END_YEAR){
  tmp <- read.csv(paste0("csv/processed_", year, ".csv"))
  tmp$year <- year
  df <- rbind(df, tmp)
  count_applications[[year - START_YEAR + 1]] <- nrow(data.frame(tmp))
}
num_applications <- data.frame(year=START_YEAR:END_YEAR)
num_applications['total_applications'] <- unlist(count_applications)
#remove 0 wage
ggplot(data=num_applications, aes(x=year, y=total_applications)) +
  geom_line()
df <- df[df$annual_wage > 0  && !is.nan(df$annual_wage),]
boxplot(annual_wage ~ year, data=df, outline=FALSE)

df$SOC_CODE <- as.character(df$SOC_CODE)
df_tmp <- df
df_tmp <- df_tmp[!is.na(df_tmp$SOC_CODE), ]
#df_tmp <- df[df$SOC_CODE <= 60, ]
df_tmp <- df_tmp[df_tmp$SOC_CODE %in% names(JOB_CODES),]
counts <- count(df_tmp, year, SOC_CODE)
counts <- transform(counts, SOC_CODE = JOB_CODES[SOC_CODE])
counts <- counts[!is.na(counts$SOC_CODE),]
ggplot(counts, aes(x=SOC_CODE, y=n)) + geom_col() + facet_wrap(~ year, ncol=2) +
  theme(axis.text.x = element_text(angle = 90, hjust=0.5))

counts <- counts[counts$SOC_CODE != 'Computer and Maths',]
ggplot(counts, aes(x=SOC_CODE, y=n)) + geom_col() + facet_wrap(~ year, ncol=2) +
  theme(axis.text.x = element_text(angle = 90, hjust=0.5))



```


